spring:
  config:
    activate:
      on-profile: db-prod

  datasource:
    url: jdbc:mysql://localhost:3306/olmago_contract
    username: olmago
    password: olmago
    driver-class-name: com.mysql.cj.jdbc.Driver
